services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3005:3000"
    networks:
      - money-sleuth
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: <%= ENV['MONEY_SLEUTH_DATABASE_PASSWORD'] %>
    ports:
      - "5433:5432"
    networks:
      - money-sleuth

networks:
  money-sleuth:
