 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/balance_entries", type: :request do
  # BalanceEntry. As you add validations to BalanceEntry, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      BalanceEntry.create! valid_attributes
      get balance_entries_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      balance_entry = BalanceEntry.create! valid_attributes
      get balance_entry_url(balance_entry)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_balance_entry_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      balance_entry = BalanceEntry.create! valid_attributes
      get edit_balance_entry_url(balance_entry)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new BalanceEntry" do
        expect {
          post balance_entries_url, params: { balance_entry: valid_attributes }
        }.to change(BalanceEntry, :count).by(1)
      end

      it "redirects to the created balance_entry" do
        post balance_entries_url, params: { balance_entry: valid_attributes }
        expect(response).to redirect_to(balance_entry_url(BalanceEntry.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new BalanceEntry" do
        expect {
          post balance_entries_url, params: { balance_entry: invalid_attributes }
        }.to change(BalanceEntry, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post balance_entries_url, params: { balance_entry: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested balance_entry" do
        balance_entry = BalanceEntry.create! valid_attributes
        patch balance_entry_url(balance_entry), params: { balance_entry: new_attributes }
        balance_entry.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the balance_entry" do
        balance_entry = BalanceEntry.create! valid_attributes
        patch balance_entry_url(balance_entry), params: { balance_entry: new_attributes }
        balance_entry.reload
        expect(response).to redirect_to(balance_entry_url(balance_entry))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        balance_entry = BalanceEntry.create! valid_attributes
        patch balance_entry_url(balance_entry), params: { balance_entry: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested balance_entry" do
      balance_entry = BalanceEntry.create! valid_attributes
      expect {
        delete balance_entry_url(balance_entry)
      }.to change(BalanceEntry, :count).by(-1)
    end

    it "redirects to the balance_entries list" do
      balance_entry = BalanceEntry.create! valid_attributes
      delete balance_entry_url(balance_entry)
      expect(response).to redirect_to(balance_entries_url)
    end
  end
end
